{{/* SPDX-FileCopyrightText: 2025 Deutsche Telekom AG

 SPDX-License-Identifier: Apache-2.0*/}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sirius.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sirius.labels" . | indent 4 }}
data:
  "config.yaml": |
{{ include "sirius.configmap" . | nindent 4 }}
