{{- if .Values.deployment.pdb.enabled -}}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sirius.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sirius.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }} 
  minAvailable: {{ .Values.deployment.pdb.minAvailable }}
{{- end -}}